# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish --configuration $(buildConfiguration)
  displayName: 'dotnet publish $(buildConfiguration)'

- task: CopyFiles@1
  inputs:
    #sourceFolder: # Optional
    #contents: '**' 
    targetFolder: $(build.artifactstagingdirectory)
    #cleanTargetFolder: false # Optional
    overWrite: true
    #flattenFolders: false # Optional
    #preserveTimestamp: false # Optional

- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- script: docker build -t $(dockerId)/$(imageName)